#!/usr/bin/env python
#-*- coding:utf-8 -*-

import os
import sys

Import('env')
#env =  env.Clone()

bench_server_bin = 'bench_server'
bench_client_bin = 'bench_client'

bench_server_sources = ['server.cc', 'bench_socket.cc', 'bench_tcp_acceptor.cc']
client_sources = ['client.cc', 'bench_client.cc', 'bench_socket.cc']

project_dir  = env['MUX_DIR']

print('\nbuild target:{0}'.format(bench_server_bin))
print(bench_server_sources)
print('\nbuild target:{0}'.format(bench_client_bin))
print(client_sources)

bin_dir = os.path.join(env['build_dir'], 'bin')

env.Program(target = os.path.join(bin_dir, bench_server_bin),
        source  = bench_server_sources,
        CPPPATH = env['headers'],
        LIBPATH = env['libs'],
        LIBS    = ['msghandler', 'muxsocket', 'mbase', 'pthread'],
        CCFLAGS = env['ccflags']
        )


env.Program(target = os.path.join(bin_dir, bench_client_bin),
        source  = client_sources,
        CPPPATH = env['headers'],
        LIBPATH = env['libs'],
        LIBS    = ['msghandler', 'muxsocket', 'mbase', 'pthread'],
        CCFLAGS = env['ccflags']
        )
