#!/usr/bin/env python
#-*- coding:utf-8 -*-

import os
import sys

Import('env')
project_dir  = env['MUX_DIR']

transport_lib  = 'transport'

transport_src_path = os.path.join(project_dir, 'transport/src')
transport_sources = []
for item in os.listdir(transport_src_path):
    if item.endswith('.cc') or item.endswith('.cpp') or item.endswith('.cxx'):
        abs_item = os.path.join(transport_src_path, item)
        transport_sources.append(abs_item)


print('\nbuild target:lib{0}.a'.format(transport_lib))
print(transport_sources)

lib_dir = os.path.join(env['build_dir'], 'lib')

link_libraries = ['epoll', 'mbase']
for lib_name in link_libraries:
    lib_name = "{0}{1}{2}".format(env['LIBPREFIX'], lib_name, env['LIBSUFFIX'])
    abs_lib_name = os.path.join(lib_dir, lib_name)
    transport_sources.append(abs_lib_name)

env.StaticLibrary(target = os.path.join(lib_dir, transport_lib),
        source  = transport_sources,
        CPPPATH = env['headers'], # include
        LIBS    = [],    # link lib
        LIBPATH = env['libs'],    # lib path
        CCFLAGS = env['ccflags']
        )
