#!/usr/bin/env python
#-*- coding:utf-8 -*-

import os
import sys

Import('env')
#env =  env.Clone()

epoll_server = ['echo_server.cc', '../../transport/tcp_transport.cc', '../../epoll/epoll_tcp_client.cc', '../../epoll/epoll_tcp_server.cc']
epoll_client = ['client.cc', '../../transport/tcp_transport.cc', '../../epoll/epoll_tcp_client.cc', '../../epoll/epoll_tcp_server.cc']

project_dir  = env['MUX_DIR']
bin_dir = os.path.join(project_dir, "sbuild/bin")

env.Program(target = os.path.join(bin_dir, "echo_server"),
        source  = epoll_server,
        CPPPATH = env['headers'],
        LIBPATH = env['libs'],
        LIBS    = ['pthread'],
        CCFLAGS = env['ccflags']
        )


env.Program(target = os.path.join(bin_dir, "echo_client"),
        source  = epoll_client,
        CPPPATH = env['headers'],
        LIBPATH = env['libs'],
        LIBS    = ['pthread'],
        CCFLAGS = env['ccflags']
        )
