#!/usr/bin/env python
#-*- coding:utf-8 -*-

import os
import sys

Import('env')
project_dir  = env['MUX_DIR']

message_handle_lib  = 'msghandler'

message_handle_src_path = os.path.join(project_dir, 'message_handle/src')
message_handle_sources = []
for item in os.listdir(message_handle_src_path):
    if item.endswith('.cc') or item.endswith('.cpp') or item.endswith('.cxx'):
        abs_item = os.path.join(message_handle_src_path, item)
        message_handle_sources.append(abs_item)

print('\nbuild target:lib{0}.a'.format(message_handle_lib))
print(message_handle_sources)

lib_dir = os.path.join(env['build_dir'], 'lib')

link_libraries = ['mbase']
for lib_name in link_libraries:
    lib_name = "{0}{1}{2}".format(env['LIBPREFIX'], lib_name, env['LIBSUFFIX'])
    abs_lib_name = os.path.join(lib_dir, lib_name)
    message_handle_sources.append(abs_lib_name)

env.StaticLibrary(target = os.path.join(lib_dir, message_handle_lib),
        source  = message_handle_sources,
        CPPPATH = env['headers'], # include
        LIBPATH = env['libs'],    # lib path
        LIBS    = ['mbase'],    # link lib
        CCFLAGS = env['ccflags']
        )
